name: build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run build with Gradle wrapper
        run: ./gradlew assembleRelease

      - name: List Output APKs (Diagnostics)
        run: ls -R app/build/outputs/apk/release

      - name: Sign app APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          alias: ${{ secrets.ALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Prepare Release Notes
        id: get_history
        run: |
          if [ -f "RELEASE_NOTES.md" ]; then
            cat RELEASE_NOTES.md > history.md
          else
            git log -n 5 --oneline > history.md
          fi

      - name: Rename APK for Release
        run: |
          mv ${{ steps.sign_app.outputs.signedReleaseFile }} app/build/outputs/apk/release/ExclusiveTV-v1.2.0-signed.apk

      - name: Create and Upload GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: history.md
          files: app/build/outputs/apk/release/ExclusiveTV-v1.2.0-signed.apk
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Gitee Create Release
        run: |
          latest_commit=$(git rev-parse HEAD)
          history=$(cat history.md)
          curl -v POST https://gitee.com/api/v5/repos/${{ github.repository }}/releases \
          -H "Content-Type: application/json" \
          -d '{
            "access_token": "${{ secrets.GITEE_ACCESS_TOKEN}}",
            "tag_name": "${{ github.ref_name }}",
            "name": "Release ${{ github.ref_name }}",
            "body": "'"$history"'",
            "prerelease": false,
            "target_commitish": "'"$latest_commit"'"
          }'